version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/authdb?schema=public
      JWT_SECRET: supersecretdev
      BASE_URL: http://localhost:4000
      FRONTEND_URL: http://localhost:3000
      GOOGLE_CLIENT_ID: your_google_id
      GOOGLE_CLIENT_SECRET: your_google_secret
    ports:
      - '4000:4000'
    command: ["npm", "run", "start"]

volumes:
  db-data:
